#!/usr/bin/env php
<?php
declare(strict_types=1);

use Arkitect\CLI\Application;
use Arkitect\CLI\Check;
use Arkitect\CLI\Command\Init;
use Arkitect\CLI\Version;

require __DIR__ . '/../vendor/autoload.php';

$application = new Application('PHPArkitect', Version::get());

$application->add(new Check());
$application->add(new Init());

$application->run();